### ISSUE TITLE
Panic upon config call with substores.

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1458]
### Summary

When running `gopass config` on a password-store with a config file coming from a previous version and a substore, here is what happened to me:
```
gopass config
root store config:
  autoclip: true
  autoimport: true
  cliptimeout: 45
  confirm: false
  editrecipients: false
  exportkeys: false
  nocolor: false
  nopager: false
  notifications: true
  path: /home/anomalroil/password-store
  safecontent: true
mount 'test' => '/home/anomalroil/test'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x561459926f24]

goroutine 1 [running]:
github.com/gopasspw/gopass/internal/store/leaf.(*Store).Storage(...)
	/home/anomalroil/go/src/github.com/gopasspw/gopass/internal/store/leaf/store.go:163
github.com/gopasspw/gopass/internal/action.(*Action).getOnDiskStorage(0xc000205340, 0x561459ec4300, 0xc000343290, 0x0, 0x0, 0x2, 0x2)
	/home/anomalroil/go/src/github.com/gopasspw/gopass/internal/action/config.go:116 +0x134
github.com/gopasspw/gopass/internal/action.(*Action).printConfigValues(0xc000205340, 0x561459ec4300, 0xc000343290, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/anomalroil/go/src/github.com/gopasspw/gopass/internal/action/config.go:60 +0x18a
github.com/gopasspw/gopass/internal/action.(*Action).Config(0xc000205340, 0xc000366b80, 0x0, 0xc0002f14f0)
	/home/anomalroil/go/src/github.com/gopasspw/gopass/internal/action/config.go:21 +0x598
github.com/urfave/cli/v2.(*Command).Run(0xc0001f70e0, 0xc000366a80, 0x0, 0x0)
	/home/anomalroil/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e2
github.com/urfave/cli/v2.(*App).RunContext(0xc000001c80, 0x561459ec4300, 0xc000343290, 0xc0001a6020, 0x2, 0x2, 0x0, 0x0)
	/home/anomalroil/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x816
main.main()
	src/github.com/gopasspw/gopass/main.go:83 +0x420
```
### Steps To Reproduce
Have a mounted substore and then do:
``` 
gopass config
``` 

### Solution
This was introduced by the refactoring done #1391 

(Fix is incoming as a PR soon.)

**Comment by dominikschulz** [comment]
Thank you for reporting this issue and working on a fix.
This is something I believed to be covered by integration tests.

**Comment by AnomalRoil** [comment]
It will be covered in a few minutes :)
