### ISSUE TITLE
Runtime error when selecting nonexistent entry in selectionWizard

### ISSUE THREAD

**Issue by alxndr13** [gopasspw/gopass#1646]
### Summary

Lets assume you have three secrets in your store:
- secretnameone
- secretnametwo
- secretnamethree

When using `gopass show secretname` you correctly get the slection wizard. But if you select a number higher (in our case here 4 or 5) than the highest shown entry then gopass will crash.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5642cb953be5]

goroutine 1 [running]:
github.com/gopasspw/gopass/internal/cui.GetSelection(0x5642cc5c4ae0, 0xc000203380, 0x5642cbf04b95, 0x26, 0xc000fac000, 0x2e, 0x50, 0x5642cc47c6a0, 0x5642cbfc7ec8, 0x0)
	github.com/gopasspw/gopass/internal/cui/cui.go:31 +0x245
github.com/gopasspw/gopass/internal/action.(*Action).findSelection(0xc000da0af0, 0x5642cc5c4ae0, 0xc000203380, 0xc0002a3740, 0xc000fac000, 0x2e, 0x50, 0x7fff7d43810d, 0x7, 0xc0005b7988, ...)
	github.com/gopasspw/gopass/internal/action/find.go:104 +0xf3
github.com/gopasspw/gopass/internal/action.(*Action).find(0xc000da0af0, 0x5642cc5c4ae0, 0xc000203380, 0xc0002a3740, 0x7fff7d43810d, 0x7, 0xc0005b7988, 0x37, 0x0)
	github.com/gopasspw/gopass/internal/action/find.go:91 +0x39d
github.com/gopasspw/gopass/internal/action.(*Action).findCmd(0xc000da0af0, 0xc0002a3740, 0xc0005b7988, 0x0, 0x0)
	github.com/gopasspw/gopass/internal/action/find.go:43 +0x205
github.com/gopasspw/gopass/internal/action.(*Action).Find(0xc000da0af0, 0xc0002a3740, 0x5642cbf06942, 0x28)
	github.com/gopasspw/gopass/internal/action/find.go:26 +0x5a
github.com/gopasspw/gopass/internal/action.(*Action).showHandleError(0xc000da0af0, 0x5642cc5c4ae0, 0xc000203380, 0xc0002a3740, 0x7fff7d43810d, 0x7, 0x1, 0x5642cc5b4640, 0xc00000e420, 0x5642cb71817a, ...)
	github.com/gopasspw/gopass/internal/action/show.go:264 +0x465
github.com/gopasspw/gopass/internal/action.(*Action).show(0xc000da0af0, 0x5642cc5c4ae0, 0xc000203380, 0xc0002a3740, 0x7fff7d43810d, 0x7, 0x1, 0x0, 0x0)
	github.com/gopasspw/gopass/internal/action/show.go:86 +0x205
github.com/gopasspw/gopass/internal/action.(*Action).Show(0xc000da0af0, 0xc0002a3740, 0x0, 0x0)
	github.com/gopasspw/gopass/internal/action/show.go:61 +0x185
github.com/urfave/cli/v2.(*Command).Run(0xc000da8900, 0xc0002a3280, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000561200, 0x5642cc5c4ae0, 0xc0004a2b40, 0xc000032180, 0x3, 0x3, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x830
main.main()
	github.com/gopasspw/gopass/main.go:95 +0x474
```

### Steps To Reproduce

see summary.

### Expected behavior

Correct handling of the user input error. 

### Environment

- OS: Manjaro Linux 
- OS version: Linux dir31n901 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux
- gopass Version: 1.10.1
- Installation method: AUR

I'l try to fix it on my own an create a PR in the next few days.

**Comment by alxndr13** [comment]
Nevermind, Duplicate of #1604. Already fixed in master.
