### ISSUE TITLE
[Bug] Go get compiling GoPass fails on M1 MacBook Air

### ISSUE THREAD

**Issue by wakatara** [gopasspw/gopass#1753]
### Summary

I get a fatal error when attempting to `go get...` Gopass on a new M1 Apple Silicon MacBook Air.

### Steps To Reproduce

Completely fresh install as porting over to a new machine.

1. Go installed via homebrew on OSX using Rosetta2 (so amd64 arch not ARM)
2. Go 1.15.7 installed
3. `GO111MODULE=on go get github.com/gopasspw/gopass`
4. Get a fatal error thrown on #github.com/jsimonetti/pwscheme/ssha512

### Expected behavior

Program should install as normal and allow me to get to my passwords. :-) 

### Environment

- OS: 11.1 Big Sur
- OS version: Darwin cassius.lan 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 x86_64 (note: this is running in Rosetta2 the processor is a new M1 Apple Silicon)
- gopass Version: v1.11.0
- Installation method: go get

### Additional context

Terminal output from the command:

```
λ ~ GO111MODULE=on go get github.com/gopasspw/gopass
go: downloading github.com/gopasspw/gopass v1.11.0
go: github.com/gopasspw/gopass upgrade => v1.11.0
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/mattn/go-colorable v0.1.7
go: downloading github.com/google/go-cmp v0.5.2
go: downloading github.com/godbus/dbus v0.0.0-20190623212516-8a1682060722
go: downloading github.com/atotto/clipboard v0.1.2
go: downloading github.com/martinhoefling/goxkcdpwgen v0.0.0-20190331205820-7dc3d102eca3
go: downloading github.com/blang/semver v0.0.0-20190414182527-1a9109f8c4a1
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/gokyle/twofactor v1.0.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mitchellh/go-ps v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading filippo.io/age v1.0.0-beta4
go: downloading github.com/muesli/crunchy v0.4.0
go: downloading github.com/schollz/closestmatch v0.0.0-20190308193919-1fbe626be92e
go: downloading golang.org/x/sys v0.0.0-20201024232916-9f70ab9862d5
go: downloading github.com/urfave/cli/v2 v2.2.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/jsimonetti/pwscheme v0.0.0-20160922125227-76804708ecad
go: downloading golang.org/x/crypto v0.0.0-20200930160638-afb6bcd081ae
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/caspr-io/yamlpath v0.0.0-20200722075116-502e8d113a9b
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading rsc.io/qr v0.2.0
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/minio/minio-go/v7 v7.0.7
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/dominikschulz/github-releases v0.0.3
go: downloading github.com/xrash/smetrics v0.0.0-20200730060457-89a2a8a1fb0b
go: downloading github.com/nbutton23/zxcvbn-go v0.0.0-20180912185939-ae427f1e4c1d
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: downloading github.com/google/uuid v1.1.1
go: downloading golang.org/x/net v0.0.0-20201021035429-f5854403a974
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading gopkg.in/ini.v1 v1.60.1
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/text v0.3.3
# github.com/jsimonetti/pwscheme/ssha512
fatal error: index out of range

goroutine 21 [running]:
runtime.throw(0x184e500, 0x12)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc0000396e0 sp=0xc0000396b0 pc=0x1035e32
runtime.panicCheck1(0x101c9e5, 0x184e500, 0x12)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:34 +0xdd fp=0xc000039710 sp=0xc0000396e0 pc=0x103349d
runtime.goPanicIndex(0xc000082a80, 0x4)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:87 +0x45 fp=0xc000039758 sp=0xc000039710 pc=0x1033585
runtime: unexpected return pc for runtime.gcBgMarkWorker called from 0x0
stack: frame={sp:0xc000039758, fp:0xc0000397d0} stack=[0xc000039000,0xc000039800)
000000c000039658:  0000000000000da0  0000000000000000 
000000c000039668:  0000000000000016  0000000001036017 <runtime.fatalthrow+87> 
000000c000039678:  000000c000039680  00000000010653e0 <runtime.fatalthrow.func1+0> 
000000c000039688:  000000c000082a80  0000000001035e32 <runtime.throw+114> 
000000c000039698:  000000c0000396b0  000000c0000396d0 
000000c0000396a8:  0000000001035e32 <runtime.throw+114>  000000c0000396b8 
000000c0000396b8:  0000000001065340 <runtime.throw.func1+0>  000000000184e500 
000000c0000396c8:  0000000000000012  000000c000039700 
000000c0000396d8:  000000000103349d <runtime.panicCheck1+221>  000000000184e500 
000000c0000396e8:  0000000000000012  0000000000000008 
000000c0000396f8:  0000000000000001  000000c000039748 
000000c000039708:  0000000001033585 <runtime.goPanicIndex+69>  000000000101c9e5 <runtime.gcBgMarkWorker+453> 
000000c000039718:  000000000184e500  0000000000000012 
000000c000039728:  000000000106d8a0 <runtime.nanotime_trampoline+0>  000000c000039740 
000000c000039738:  00000000f70d7ea1  00001743f70d7ea1 
000000c000039748:  000000c0000397c8  000000000101c9e5 <runtime.gcBgMarkWorker+453> 
000000c000039758: <000000c000082a80  0000000000000004 
000000c000039768:  000000c000016210  0000000000001418 
000000c000039778:  0000000000000000  0000000000000000 
000000c000039788:  0000000000000000  00001743f70d7ea1 
000000c000039798:  0000000000000000  000000c000082a80 
000000c0000397a8:  000000c000016210  00000000010638a0 <runtime.gcBgMarkWorker.func2+0> 
000000c0000397b8:  000000c000082a80  000000c000033000 
000000c0000397c8: !0000000000000000 >000000000106c0e1 <runtime.goexit+1> 
000000c0000397d8:  000000c000033000  0000000000000000 
000000c0000397e8:  0000000000000000  0000000000000000 
000000c0000397f8:  0000000000000000 
runtime.nanotime(...)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/time_nofake.go:19
runtime.gcBgMarkWorker(0x106c0e1)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/mgc.go:1987 +0x1c5 fp=0xc0000397d0 sp=0xc000039758 pc=0x101c9e5
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/mgc.go:1839 +0x77

goroutine 1 [runnable]:
cmd/compile/internal/gc.peekitabs()
	/usr/local/Cellar/go/1.15.7/libexec/src/cmd/compile/internal/gc/reflect.go:1418 +0xfa
cmd/compile/internal/gc.Main(0x186bb88)
	/usr/local/Cellar/go/1.15.7/libexec/src/cmd/compile/internal/gc/main.go:738 +0x3396
main.main()
	/usr/local/Cellar/go/1.15.7/libexec/src/cmd/compile/main.go:52 +0xb1
```

**Comment by dominikschulz** [comment]
This is not a gopass issue. I don't believe it's a dependency issue either.
Please wait for [go 1.16](https://blog.golang.org/ports) and/or report a bug to the Go team.

Feel free to re-open if you're absolutely sure that it's a gopass specific issue.
But please note that I don't have access to Apple Silicon at the moment and I don't think I will have any time soon.

**Comment by wakatara** [comment]
Apologies, I honestly did not realize there was an issue with M1 Arm support in Go. Will wait till 1.16. gopass seems to work fine as a `brew install` under AMD64 and working fine now. Thanks for all your work on gp.

**Comment by dominikschulz** [comment]
No worries. If it's truly a gopass bug please reopen and I'll be happy to take a look.

**Comment by wakatara** [comment]
Just to let you know, this appears to now compile and install normally via 
`GO111MODULE=on go get github.com/gopasspw/gopass`

**Comment by dominikschulz** [comment]
Thanks a lot for reporting back!
