### ISSUE TITLE
Interacting with Gopass leads to random go stacktraces on OsX

### ISSUE THREAD

**Issue by Tartori** [gopasspw/gopass#2429]
### Summary

After upgrading to gopass 1.14.10 on osx it started to crash randomly. I attached the trace that is printed. I tried killing the gpg agent but it does not help.

### Steps To Reproduce
use any gopass command (even gopass version sometimes crashes)

### Expected behavior
There to be no error :D

### Environment

- OS: macOS Monterey 12.6.1
- OS version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
- gopass Version: gopass 1.14.10 go1.19.3 darwin amd64
- Installation method: brew

### Additional context

```
Error: failed to retrieve secret "personal/artifactory_key": failed to decrypt
runtime: nameOff 0x34312e31 base 0xd2177b0 not in ranges:
	types 0xd22a000 etypes 0xd3b0ce8
fatal error: runtime: name offset base pointer out of range

goroutine 50 [running]:
runtime.throw({0xd1375a7?, 0x0?})
	runtime/panic.go:1047 +0x5d fp=0xc000642c28 sp=0xc000642bf8 pc=0xcb11cbd
runtime.resolveNameOff(0x0?, 0x34312e31)
	runtime/type.go:221 +0x1d6 fp=0xc000642c80 sp=0xc000642c28 pc=0xcb3a936
runtime.(*_type).nameOff(...)
	runtime/type.go:227
runtime.(*_type).string(0xd2177b0)
	runtime/type.go:55 +0x25 fp=0xc000642ca0 sp=0xc000642c80 pc=0xcb3a5c5
runtime.(*TypeAssertionError).Error(0xc00009a810)
	runtime/error.go:39 +0x9e fp=0xc000642da8 sp=0xc000642ca0 pc=0xcae417e
runtime.preprintpanics(0xc000560140?)
	runtime/panic.go:581 +0x7f fp=0xc000642e08 sp=0xc000642da8 pc=0xcb10b1f
panic({0xd2b5c20, 0xc00009a810})
	runtime/panic.go:985 +0x3ac fp=0xc000642ec8 sp=0xc000642e08 pc=0xcb1186c
runtime.panicdottypeE(0xd2177b0, 0xd277e40, 0xd299100)
	runtime/iface.go:262 +0x6a fp=0xc000642ee8 sp=0xc000642ec8 pc=0xcae6b2a
context.(*cancelCtx).Done(0x0?)
	context/context.go:361 +0x1d4 fp=0xc000642f68 sp=0xc000642ee8 pc=0xcb6ec74
main.main.func2()
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:74 +0x3b fp=0xc000642fe0 sp=0xc000642f68 pc=0xd0f601b
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000642fe8 sp=0xc000642fe0 pc=0xcb43ee1
created by main.main
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:70 +0x1db

goroutine 1 [runnable]:
runtime.gcTrigger.test({0x0?, 0x0?, 0x0?})
	runtime/mgc.go:548 +0xfc fp=0xc00046dba0 sp=0xc00046db98 pc=0xcaf585c
runtime.mallocgc(0x30, 0xd33cae0, 0x1)
	runtime/malloc.go:1137 +0x7fd fp=0xc00046dc18 sp=0xc00046dba0 pc=0xcae957d
runtime.newobject(0xc000580000?)
	runtime/malloc.go:1192 +0x27 fp=0xc00046dc40 sp=0xc00046dc18 pc=0xcae9767
runtime.makemap(0xc00046dcc8?, 0xcbb972f?, 0x0?)
	runtime/map.go:312 +0x5b fp=0xc00046dc88 sp=0xc00046dc40 pc=0xcaea3bb
github.com/gopasspw/gopass/internal/store/root.New(0x7ff7b4423730?)
	github.com/gopasspw/gopass/internal/store/root/store.go:32 +0x4f fp=0xc00046dce0 sp=0xc00046dc88 pc=0xcf873ef
github.com/gopasspw/gopass/internal/action.newAction(0xc000594000, {0x1, 0xe, 0xa, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, ...)
	github.com/gopasspw/gopass/internal/action/action.go:45 +0x6f fp=0xc00046dd50 sp=0xc00046dce0 pc=0xd0aa68f
github.com/gopasspw/gopass/internal/action.New(...)
	github.com/gopasspw/gopass/internal/action/action.go:32
main.setupApp({0xd3727d0, 0xc00054c300}, {0x1, 0xe, 0xa, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}})
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:108 +0xb4 fp=0xc00046de00 sp=0xc00046dd50 pc=0xd0f6194
main.main()
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:87 +0x407 fp=0xc00046df80 sp=0xc00046de00 pc=0xd0f5ee7
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc00046dfe0 sp=0xc00046df80 pc=0xcb144d2
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00046dfe8 sp=0xc00046dfe0 pc=0xcb43ee1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00005cfb0 sp=0xc00005cf90 pc=0xcb14896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.forcegchelper()
	runtime/proc.go:302 +0xad fp=0xc00005cfe0 sp=0xc00005cfb0 pc=0xcb1472d
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0xcb43ee1
created by runtime.init.6
	runtime/proc.go:290 +0x25

goroutine 17 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000058790 sp=0xc000058770 pc=0xcb14896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:297 +0xd7 fp=0xc0000587c8 sp=0xc000058790 pc=0xcb007f7
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc0000587e0 sp=0xc0000587c8 pc=0xcaf5466
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000587e8 sp=0xc0000587e0 pc=0xcb43ee1
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 18 [GC scavenge wait]:
runtime.gopark(0xc000036070?, 0xd2177c0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000058f70 sp=0xc000058f50 pc=0xcb14896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.(*scavengerState).park(0xd7e0300)
	runtime/mgcscavenge.go:389 +0x53 fp=0xc000058fa0 sp=0xc000058f70 pc=0xcafe853
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:622 +0x65 fp=0xc000058fc8 sp=0xc000058fa0 pc=0xcafee45
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc000058fe0 sp=0xc000058fc8 pc=0xcaf5406
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0xcb43ee1
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 19 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000059628 sp=0xc000059608 pc=0xcb14896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.runfinq()
	runtime/mfinal.go:180 +0x10f fp=0xc0000597e0 sp=0xc000059628 pc=0xcaf456f
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0xcb43ee1
created by runtime.createfing
	runtime/mfinal.go:157 +0x45

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000059f50 sp=0xc000059f30 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000059fe0 sp=0xc000059f50 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x1391f34fad46?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000508750 sp=0xc000508730 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0005087e0 sp=0xc000508750 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0005087e8 sp=0xc0005087e0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x1391f1b27b20?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00005a750 sp=0xc00005a730 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00005a7e0 sp=0xc00005a750 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 3 [GC worker (idle)]:
runtime.gopark(0x1391f3499295?, 0xc00006a010?, 0x40?, 0x78?, 0xc000036070?)
	runtime/proc.go:363 +0xd6 fp=0xc00005c750 sp=0xc00005c730 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00005c7e0 sp=0xc00005c750 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x1391f3499517?, 0x3?, 0x5a?, 0x83?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00005af50 sp=0xc00005af30 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00005afe0 sp=0xc00005af50 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005afe8 sp=0xc00005afe0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1391f3510b3f?, 0x3?, 0x21?, 0x9c?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000508f50 sp=0xc000508f30 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000508fe0 sp=0xc000508f50 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000508fe8 sp=0xc000508fe0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1391f24afc7c?, 0x1?, 0xb9?, 0x23?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000509750 sp=0xc000509730 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0005097e0 sp=0xc000509750 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0005097e8 sp=0xc0005097e0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 4 [GC worker (idle)]:
runtime.gopark(0x1391f24aea6d?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00005d750 sp=0xc00005d730 pc=0xcb14896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00005d7e0 sp=0xc00005d750 pc=0xcaf75b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0xcb43ee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 23 [select, locked to thread]:
runtime.gopark(0xc00050bfa8?, 0x2?, 0x17?, 0x4c?, 0xc00050bfa4?)
	runtime/proc.go:363 +0xd6 fp=0xc00050be20 sp=0xc00050be00 pc=0xcb14896
runtime.selectgo(0xc00050bfa8, 0xc00050bfa0, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc00050bf60 sp=0xc00050be20 pc=0xcb244fc
runtime.ensureSigM.func1()
	runtime/signal_unix.go:991 +0x187 fp=0xc00050bfe0 sp=0xc00050bf60 pc=0xcb28a27
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00050bfe8 sp=0xc00050bfe0 pc=0xcb43ee1
created by runtime.ensureSigM
	runtime/signal_unix.go:974 +0xbd

goroutine 49 [syscall]:
runtime.sigNoteSleep(0x0)
	runtime/os_darwin.go:123 +0x1e fp=0xc0005067a0 sp=0xc000506768 pc=0xcb0ed3e
os/signal.signal_recv()
	runtime/sigqueue.go:149 +0x28 fp=0xc0005067c0 sp=0xc0005067a0 pc=0xcb3ff08
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19 fp=0xc0005067e0 sp=0xc0005067c0 pc=0xcbcd799
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0005067e8 sp=0xc0005067e0 pc=0xcb43ee1
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 51 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000507698 sp=0xc000507678 pc=0xcb14896
runtime.chanrecv(0xc00058c1e0, 0xc0005077a0, 0x1)
	runtime/chan.go:583 +0x49b fp=0xc000507728 sp=0xc000507698 pc=0xcae27fb
runtime.chanrecv2(0x0?, 0x0?)
	runtime/chan.go:447 +0x18 fp=0xc000507750 sp=0xc000507728 pc=0xcae2338
github.com/gopasspw/gopass/internal/queue.(*Queue).run(0xc00018a3b0, {0xd372728, 0xc000220140})
	github.com/gopasspw/gopass/internal/queue/background.go:85 +0x70 fp=0xc0005077b8 sp=0xc000507750 pc=0xcf4dff0
github.com/gopasspw/gopass/internal/queue.New.func1()
	github.com/gopasspw/gopass/internal/queue/background.go:79 +0x2e fp=0xc0005077e0 sp=0xc0005077b8 pc=0xcf4df4e
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0005077e8 sp=0xc0005077e0 pc=0xcb43ee1
created by github.com/gopasspw/gopass/internal/queue.New
	github.com/gopasspw/gopass/internal/queue/background.go:79 +0x10d
gpg: public key decryption failed: Screen or window too small
gpg: decryption failed: Screen or window too small
❌ Decryption failed: exit status 2
```

**Comment by dominikschulz** [comment]
I don't see how this could be a gopass specific defect.

I found this old Go issue that might be related: https://github.com/golang/go/issues/37712

**Comment by dominikschulz** [comment]
I wonder if this might be related to https://github.com/gopasspw/gopass/issues/2325
