### ISSUE TITLE
runtime error on `gopass --generate-bash-completion`

### ISSUE THREAD

**Issue by tagirb** [gopasspw/gopass#864]
### Summary
gpg went missing from my system due to some weird Homebrew behavior. Then, bash completion stopped worked on `gopass<TAB>`. This triggered calling `gopass --generate-bash-completion`, which exits with a runtime error.

### Steps To Reproduce
```
$ which gpg
gpg not found
$ gopass --generate-bash-completion
agent
audit
binary
bin
clone
completion
config
copy
cp
create
new
delete
remove
rm
edit
set
find
search
fsck
generate
git-credential
otp
totp
hotp
git
grep
history
hist
init
insert
list
ls
move
mv
mounts
recipients
show
sync
templates
update
version
xc
help
h
Faild to initialize stores: failed to initialize the root store at 'gpgcli-gitcli-fs+file:///Users/tagir/git/password-store/root': failed to init crypto backend: no gpg binary found: no gpg binary found: failed to init crypto backend: no gpg binary found: no gpg binary found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x10ec994fa]

goroutine 1 [running]:
github.com/gopasspw/gopass/pkg/store/sub.(*Store).List(0x0, 0x10f0fe620, 0xc4202ba570, 0x0, 0x0, 0x0, 0xc42016da80, 0x10e82ada7, 0xc420310000, 0xc4202d4200)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/pkg/store/sub/list.go:17 +0x3a
github.com/gopasspw/gopass/pkg/store/root.(*Store).Tree(0xc420082380, 0x10f0fe620, 0xc4202ba570, 0x1e, 0xc420069130, 0x1, 0x1)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/pkg/store/root/list.go:56 +0x1ad
github.com/gopasspw/gopass/pkg/store/root.(*Store).List(0xc420082380, 0x10f0fe620, 0xc4202ba570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/pkg/store/root/list.go:18 +0x43
github.com/gopasspw/gopass/pkg/action.(*Action).Complete(0xc4202e0fc0, 0x10f0fe620, 0xc4202ba570, 0xc42031e000)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/pkg/action/completion.go:30 +0x96
main.setupApp.func1(0xc42031e000)
	src/github.com/gopasspw/gopass/app.go:58 +0x72
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.ShowCompletions(0xc42031e000)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/help.go:224 +0x49
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.checkCompletions(0xc42031e000, 0xc42031e000)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/help.go:334 +0x7c
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc4202f8000, 0xc4200c2000, 0x1, 0x2, 0x0, 0x0)
	/private/tmp/gopass-20180608-28807-qxx3yy/gopass-1.8.1/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/app.go:206 +0x351
main.main()
	src/github.com/gopasspw/gopass/main.go:64 +0x2d7
```

### Expected behavior
The completion to give back the possible arguments.

### Environment
- OS: macOS High Sierra 10.13.5
- OS version: `Darwin mbp-tba 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
- gopass Version: 1.8.1
- Installation method: brew

**Comment by dominikschulz** [comment]
Hmm, thanks for reporting. This should not happend, obviously. Will investigate.
