### ISSUE TITLE
windows: crashes when called from gopassbridge

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#974]
### Summary
`gopass` and gopassbridge are not working under Windows

### Steps To Reproduce
* Run `gopass` from `cmd.exe`: it works.
* Configure Chrome with a native messaging host.
* Run Chrome with `--enable-logging --v=1`
* Activate the extension

Note that the `gopass.exe` binary, renamed to `gopass_native_host.exe` has crashed:
```
C:\Users\colem>"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 1" --enable-logging --v=1

C:\Users\colem>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x94fa31]

goroutine 1 [running]:
github.com/gopasspw/gopass/pkg/store/sub.(*Store).List(0x0, 0xdb03c0, 0xc0421fd050, 0x0, 0x0, 0xc0421fab60, 0x3, 0xc04203a570, 0xc04203a500, 0xc04207e058)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/store/sub/list.go:17 +0x41
github.com/gopasspw/gopass/pkg/store/root.(*Store).Tree(0xc0421fcc90, 0xdb03c0, 0xc0421fd050, 0xb7bf80, 0xc04215f960, 0x0, 0x0)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/store/root/list.go:56 +0x1b4
github.com/gopasspw/gopass/pkg/store/root.(*Store).List(0xc0421fcc90, 0xdb03c0, 0xc0421fd050, 0x0, 0xc04215f960, 0x0, 0x0, 0x16, 0xc0420a1a78)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/store/root/list.go:18 +0x4a
github.com/gopasspw/gopass/pkg/jsonapi.(*API).respondHostQuery(0xc0420a1bd8, 0xdb03c0, 0xc0421fd050, 0xc042096d20, 0x24, 0x24, 0x0, 0xc0420a2000)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/jsonapi/responses.go:50 +0xd6
github.com/gopasspw/gopass/pkg/jsonapi.(*API).respondMessage(0xc0420a1bd8, 0xdb03c0, 0xc0421fd050, 0xc042096d20, 0x24, 0x24, 0x0, 0x5)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/jsonapi/responses.go:32 +0x33c
github.com/gopasspw/gopass/pkg/jsonapi.(*API).ReadAndRespond(0xc0420a1bd8, 0xdb03c0, 0xc0421fccf0, 0xc0420a1c00, 0xb1fa7b)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/jsonapi/api.go:26 +0xdf
github.com/gopasspw/gopass/pkg/action.(*Action).JSONAPI(0xc0422a6af0, 0xdb03c0, 0xc0421fccf0, 0xc0420dd1e0, 0xc0421fccf0, 0x0)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/pkg/action/jsonapi.go:26 +0x9e
main.setupApp.func2(0xc0420dd1e0, 0x0, 0x0)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/app.go:54 +0xdf
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.HandleAction(0xbbacc0, 0xc0421a8e20, 0xc0420dd1e0, 0x0, 0x0)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/app.go:501 +0xcf
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc0421721c0, 0xc04207e080, 0x3, 0x4, 0x0, 0x0)
        /Users/tex/src/go/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/app.go:268 +0x613
main.main()
        /Users/tex/src/go/src/github.com/gopasspw/gopass/main.go:64 +0x2de

```

### Expected behavior
It works.

### Environment

- OS: Windows 10
- OS version: `Microsoft Windows [Version 10.0.18277.1000]`
- gopass Version:
   ```
   gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04) go1.10 windows amd64
   <root>     - gpg 2.2.10 -  git 0.0.0 -   fs 0.1.0
   ``` 
- Installation method: from github releases

**Comment by colemickens** [comment]
My mistake again, I didn't realize how old the current release was. Built the new one and everything works including the auto-install. Very nice. Thanks for `gopass` btw!
