### ISSUE TITLE
Path handling is different and tests fail in Windows

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#982]
### Summary
The way lookups are done through the jsonapi (queryHost) behaves differently on Windows than on Linux.

Accordingly, a number of the jsonapi tests fail on Windows.

Unfortunately, I don't have time to dig into this. FWIW, the only manifestation I can see is that the browser extension fails to find matches in some cases.

For example, when the browser is on `account.ubnt.com`:
* in Windows: no entries
* in Linux: `colemickens/ubnt.com` is returned

Also,

```
--- FAIL: TestRespondMessageQuery (1.95s)
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:75
        	Error:      	Expect "["awesomePrefix\\foo\\bar"]" to match "\["awesomePrefix/foo/bar"\]"
        	Test:       	TestRespondMessageQuery
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:81
        	Error:      	Expect "["awesomePrefix\\fixed\\yamllogin","awesomePrefix\\fixed\\yamlother"]" to match "\["awesomePrefix/fixed/yamllogin","awesomePrefix/fixed/yamlother"\]"
        	Test:       	TestRespondMessageQuery
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:87
        	Error:      	Expect "[]" to match "\["awesomePrefix/b/some.other.host","awesomePrefix/some.other.host/other"\]"
        	Test:       	TestRespondMessageQuery
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:93
        	Error:      	Expect "[]" to match "\["awesomePrefix/other.host/other"\]"
        	Test:       	TestRespondMessageQuery
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:105
        	Error:      	Expect "[]" to match "\["somename/github.com"\]"
        	Test:       	TestRespondMessageQuery
    api_test.go:305: 
        	Error Trace:	api_test.go:305
        	            				api_test.go:246
        	            				api_test.go:242
        	            				api_test.go:111
        	Error:      	Expect "[]" to match "\["somename/ubnt.com"\]"
        	Test:       	TestRespondMessageQuery
FAIL
FAIL	github.com/gopasspw/gopass/pkg/jsonapi	4.326s

```

### Steps To Reproduce
Try to run jsonapi tests on Windows.

### Expected behavior
They pass.

### Environment

- OS: Windows 10
- OS version: Version 1809 OS Build 18277.1000
- gopass Version: HEAD dec28c39...
- Installation method: source

**Comment by colemickens** [comment]
Actually, this fixes the issue: https://github.com/gopasspw/gopass/pull/935

**Comment by dominikschulz** [comment]
@colemickens Could you try to run all the tests (`make travis`) with this fix applied on windows and report back? That would help a lot.

**Comment by colemickens** [comment]
There's some reasons why I hadn't done this. I can't run make in windows, the tests seem to rely on more OS-specific stuff, the tests seem to need GOPASS_BINARY set at times, I can't remember how to get go to give me a summary of test results and I'm going cross-eyed from all the output `go test` spewed at me...

Also there seem to be packages whose tests that don't even compile? Some of them panic too. I'm not sure what the state of the tests are in Linux, but they're not in good shape on Windows.

I did try just give this a shot for the last ~40 minutes... but due to what I perceive as deficits in the testing infrastructure, I can't really even venture a good guess as to whether the tests are overall better or overall worse with #953 applied. As an example, #953 makes good sense and fixes real world usage of gopass/gopassbridge, but it doesn't even fix the jsonapi tests due to how they work (string-wise path comparisons, it initializes a full new pass store on every case in every test). In general the tests are in a bad state in Windows. Some don't compile, some panic, etc.

Unfortunately, I'm not sure I can offer much more confidence in #953 than my original anecdotal comments, at least right now.

**Comment by AnomalRoil** [comment]
I just ran `go test (go list .\pkg\...)` on a Windows computer, and the log file is about 932 lines. 
There are so many tests failing that it's complicated to see what's going on.

As a fun note, when using the patch proposed in #935 these tests fail:
```
?   	github.com/gopasspw/gopass/pkg/tree	[no test files]
=== RUN   TestFolder
--- FAIL: TestFolder (0.00s)
	folder_test.go:41: 
			Error Trace:	folder_test.go:41
			Error:      	Not equal: 
			            	expected: "gopass\nÔööÔöÇÔöÇ foo (template)\n    Ôö£ÔöÇÔöÇ bar\n    Ôö£ÔöÇÔöÇ baz.b64 (binary)\n    ÔööÔöÇÔöÇ zab.yml (yaml)\n"
			            	actual  : "gopass\nÔö£ÔöÇÔöÇ foo/bar\nÔö£ÔöÇÔöÇ foo/baz.b64 (binary)\nÔööÔöÇÔöÇ foo/zab.yml (yaml)\n"
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1,6 +1,5 @@
			            	 gopass
			            	-ÔööÔöÇÔöÇ foo (template)
			            	-    Ôö£ÔöÇÔöÇ bar
			            	-    Ôö£ÔöÇÔöÇ baz.b64 (binary)
			            	-    ÔööÔöÇÔöÇ zab.yml (yaml)
			            	+Ôö£ÔöÇÔöÇ foo/bar
			            	+Ôö£ÔöÇÔöÇ foo/baz.b64 (binary)
			            	+ÔööÔöÇÔöÇ foo/zab.yml (yaml)
			            	 
			Test:       	TestFolder
	folder_test.go:55: 
			Error Trace:	folder_test.go:55
			Error:      	Not equal: 
			            	expected: []string{"zab/foozen"}
			            	actual  : []string{"zab/foo/bar", "zab/foozen", "zab2/foo/baz", "zab2/foo/zen/baz"}
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1,3 +1,6 @@
			            	-([]string) (len=1) {
			            	- (string) (len=10) "zab/foozen"
			            	+([]string) (len=4) {
			            	+ (string) (len=11) "zab/foo/bar",
			            	+ (string) (len=10) "zab/foozen",
			            	+ (string) (len=12) "zab2/foo/baz",
			            	+ (string) (len=16) "zab2/foo/zen/baz"
			            	 }
			Test:       	TestFolder
	folder_test.go:66: 
			Error Trace:	folder_test.go:66
			Error:      	Not equal: 
			            	expected: []string{"zab", "zab/foo", "zab2", "zab2/foo", "zab2/foo/zen"}
			            	actual  : []string{}
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1,7 +1,2 @@
			            	-([]string) (len=5) {
			            	- (string) (len=3) "zab",
			            	- (string) (len=7) "zab/foo",
			            	- (string) (len=4) "zab2",
			            	- (string) (len=8) "zab2/foo",
			            	- (string) (len=12) "zab2/foo/zen"
			            	+([]string) {
			            	 }
			Test:       	TestFolder
	folder_test.go:76: 
			Error Trace:	folder_test.go:76
			Error:      	Not equal: 
			            	expected: []string{"zab", "zab/foo", "zab2", "zab2/foo"}
			            	actual  : []string{}
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1,6 +1,2 @@
			            	-([]string) (len=4) {
			            	- (string) (len=3) "zab",
			            	- (string) (len=7) "zab/foo",
			            	- (string) (len=4) "zab2",
			            	- (string) (len=8) "zab2/foo"
			            	+([]string) {
			            	 }
			Test:       	TestFolder
=== RUN   TestFormat
--- FAIL: TestFormat (0.00s)
	tree_test.go:78: Format mismatch:
		---
		gopass
		Ôö£ÔöÇÔöÇ a
		Ôöé   Ôö£ÔöÇÔöÇ b
		Ôöé   Ôöé   ÔööÔöÇÔöÇ c
		Ôöé   Ôöé       Ôö£ÔöÇÔöÇ d
		Ôöé   Ôöé       ÔööÔöÇÔöÇ e
		Ôöé   Ôö£ÔöÇÔöÇ g
		Ôöé   Ôöé   ÔööÔöÇÔöÇ h
		Ôöé   ÔööÔöÇÔöÇ f
		ÔööÔöÇÔöÇ foo (E:\tmp\foo)
		    Ôö£ÔöÇÔöÇ bar (E:\tmp\bar)
		    Ôöé   ÔööÔöÇÔöÇ baz
		    ÔööÔöÇÔöÇ baz
		        ÔööÔöÇÔöÇ inga
		---
		gopass
		Ôö£ÔöÇÔöÇ foo (E:\tmp\foo)
		Ôö£ÔöÇÔöÇ foo/bar (E:\tmp\bar)
		Ôö£ÔöÇÔöÇ a/b/c/d
		Ôö£ÔöÇÔöÇ a/b/c/e
		Ôö£ÔöÇÔöÇ a/f
		Ôö£ÔöÇÔöÇ a/g/h
		Ôö£ÔöÇÔöÇ foo/bar/baz
		ÔööÔöÇÔöÇ foo/baz/inga
		---
=== RUN   TestFormatSubtree
--- FAIL: TestFormatSubtree (0.00s)
	tree_test.go:94: 
			Error Trace:	tree_test.go:94
			Error:      	Received unexpected error:
			            	Entry not found
			            	github.com/gopasspw/gopass/pkg/tree/simple.(*Folder).FindFolder
			            		E:/golang/src/github.com/gopasspw/gopass/pkg/tree/simple/folder.go:206
			            	github.com/gopasspw/gopass/pkg/tree/simple.TestFormatSubtree
			            		E:/golang/src/github.com/gopasspw/gopass/pkg/tree/simple/tree_test.go:93
			            	testing.tRunner
			            		C:/Go/src/testing/testing.go:777
			            	runtime.goexit
			            		C:/Go/src/runtime/asm_amd64.s:2361
			Test:       	TestFormatSubtree
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x6435a6]

goroutine 7 [running]:
testing.tRunner.func1(0xc0420fa2d0)
	C:/Go/src/testing/testing.go:742 +0x2a4
panic(0x688c40, 0x8520c0)
	C:/Go/src/runtime/panic.go:505 +0x237
github.com/gopasspw/gopass/pkg/tree/simple.TestFormatSubtree(0xc0420fa2d0)
	E:/golang/src/github.com/gopasspw/gopass/pkg/tree/simple/tree_test.go:96 +0x266
testing.tRunner(0xc0420fa2d0, 0x6f1620)
	C:/Go/src/testing/testing.go:777 +0xd7
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:824 +0x2e7
FAIL	github.com/gopasspw/gopass/pkg/tree/simple	0.060s
```
while using the hardcoded unix separator make them pass, but that's probably because the tests are meant to pass on unix:
```
=== RUN   TestFolder
--- PASS: TestFolder (0.00s)
=== RUN   TestFormat
--- PASS: TestFormat (0.00s)
=== RUN   TestFormatSubtree
--- PASS: TestFormatSubtree (0.00s)
=== RUN   TestGetNonExistingSubtree
--- PASS: TestGetNonExistingSubtree (0.00s)
PASS
ok      github.com/gopasspw/gopass/pkg/tree/simple```
